<?php
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
html, body{
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background-color:#008cba; 
    height:100%;
}
.container{ 
   height:100%;
   display:flex;
   align-items:center;
   justify-content:center;
}
.content{
    background-color:white;
    width:500px;
    height:700px;
}
img{
    width: 100%;
    height: 20%;
}
.form-title{
    padding:10px 40px 0px;
}
form{
    padding:0px 40px;
}
input[type=text], [type=email]{
    border: none;
    border-bottom: 1px solid black;
    outline:none;
    width:100%;
    margin: 8px 0;
    padding:10px 0;
}
input[type=number]{
    border: none;
    border-bottom: 1px solid black;
    outline:none;
    margin: 8px 0;
    padding:5px 0;
}
input :hover {
    background-color: red;
}
button{
    color:#ffffff;
    background-color: #4caf50;
    height:40px;
    width:25%;
    margin-top:15px;
    cursor: pointer;
    border:none;
    border-radius:2%;
    outline:none;
    text-align:center;
    font-size:16px;
    text-decoration:none;
    -webkit-transition-duration:0.4s;
    transition-duration:0.4s;
}
button:hover{
    background-color:#333333;
}
    </style>
</head>
<body>
<div class="container">
    <div class="content">
       <img src="https://res.cloudinary.com/debbsefe/image/upload/f_auto,c_fill,dpr_auto,e_grayscale/image_fz7n7w.webp" alt="header-image" class="cld-responsive">
            <h1 class="form-title">Add your Product</h1>
            <form action="/product/view" method="POST">
                <label for="">Product Name:
               <input type="text" name="p_name" value="<?php echo $result->name; ?>"></label>
               <label for="">Price: <input type="text" name="p_price" value="<?php echo $result->price; ?>"></label>
               <label for="">Your Name:
               <input type="text" name="name" placeholder="Customer Name"></label>
            <label for="">Contact:</label><br>
                <input type="number" name="contact" placeholder="Contact number"><br>
            <label for="">Address:
                <input type="text" name="address" placeholder="Address"></label>
                <label for="">Quantity:
                <input type="text" name="quantity" value="<?php echo $result->quantity; ?>"></label><br>
                <button type="submit" name="submit">Placed</button>
            </form>
        </div>
 </div>

</body>
</html>